## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW1_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [2]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [ ]:
# Type your solution here
import pandas as pd

#Q1-1
frame = pd.DataFrame(data)
print(frame,"\n")

#Q1-2
series1 = frame.name[((frame.job == "psychologist") | (frame.job == "teacher")) & (frame.num_cars > frame.family_size)]
print(series1,"\n")

#Q1-3
series2 = frame.name[(frame.family_size <= 2) & (frame.num_cars >= 1)]
print(series2,"\n")

#Q1-4
print(type(frame))
unique_jobs = frame.job.unique()
print(unique_jobs)

**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [ ]:
# Type your solution here

# Create a dataframe with the 2 series
df = pd.DataFrame(columns=['fruits','weights'])
df['fruits'] = fruit
df['weights'] = weights
print(df,"\n")

# Group the dataframe by fruit then calculate mean
grouped_df = df.groupby('fruits')
mean_df = grouped_df.mean()
print(mean_df)

   fruits  weights
0  banana      1.0
1  banana      2.0
2  carrot      3.0
3  carrot      4.0
4  carrot      5.0
5  carrot      6.0
6  banana      7.0
7   apple      8.0
8  banana      9.0
9  banana     10.0 

        weights
fruits         
apple       8.0
banana      5.8
carrot      4.5


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [ ]:
# Type your solution here

#Q3-1
# Sort the course_name array (not necessary, but just a sanity check)
print(np.sort(course_name), "\n")

# Use argsort to find indices of sorted elements 
sort_index = np.argsort(course_name)
print("Indices of sorted elements of course_name array:", sort_index, "\n")

#Q3-2
# Uses list comprehension to step through course_name and find values that start with P
P_indices = [i for i, si in enumerate(course_name) if si.startswith('P')]
print(course_name[P_indices])

**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [ ]:
# Type your solution here

#Q4-1
# Reverse the array then print original & reversed 
reverse_student_id = student_id[::-1]
print("Orignal array:", student_id)
print("Reversed array:", reverse_student_id)
print("\n")

#Q4-2
# Sort the array in descending order
student_id_sorted = -np.sort(-student_id)
print("3-largest values of student_id array:", student_id_sorted[0:3])


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [ ]:
# Type your solution here

# Hint: you can use arange to start off

# Create array with integers 0-99
arr = np.arange(100)

# Use enumerate to step through array & find all values divisible by 3 or 5, then add them 
print("Sum of all multiples of 3:", sum([i for i, si in enumerate(arr) if i % 3 == 0]), "\n")

print("Sum of all multiples of 5:", sum([i for i, si in enumerate(arr) if i % 5 == 0]))

**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:

#Q6-1
# Uses advanced slicing to reverse column 1 with column 2
arr[:,[0, 1]] = arr[:,[1, 0]]
print(arr)
print("\n")

#Q6-2
# Uses advanced slicing to reverse row 0 with row 1
arr[[0,1],:] = arr[[1,0],:]
print(arr)
